### ISSUE TITLE
Select * from table

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#166]
Am I missing something or is it right now not possible to select `*` from a table?

**Comment by martijndeh** [comment]
You are correct! You need to spell out all the select columns. There was simply no need for the * yet. Personally, I try to avoid it so I'm hesitant to give it a high priority. It's also a little tricky especially considering joins, table.*, etc. That being said, Mammoth should support it because it's part of SQL. Did you think of a nice syntax yet or were you just wondering?

**Comment by martijndeh** [comment]
So this just hit master:

```ts
db.select(db.listItem.star()).from(db.listItem)
```

which produces

```sql
SELECT list_item.* FROM list_item
```

I consider this question resolved and will close this issue. In next few days I'll release a new version to npm and update the documentation.

**Comment by creepinson** [comment]
Any updates on this? It says `TS2339: Property 'star' does not exist on type 'Table"routes", { id: Column"id", "routes", string, true,`

**Comment by martijndeh** [comment]
Eeks this was not published yet. 1.2.0 is available now and it should work using that version.

**Comment by AuspeXeu** [comment]
@martijndeh would probably good to also have a tag corresponding to each release so that it's easier for people to realize what code their current version is based on :)
