### ISSUE TITLE
Self referencing tables

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#167]
How would one write the correct table definition to reflect a composite pattern where a row can reference another row in the same table?

**Comment by martijndeh** [comment]
So, today, to create a references you can write the following:

```
fooId: uuid().references(foo, 'id),
```

Obviously this is not going to work when referencing to the same table you're defining and you'll get something like a "used before decoration". I think a simple fix would be something like the below. Not too sure if the column name will work like that, could even try to just return e.g. `foo.id` instead. What do you think?

```
fooId: uuid().references(() => foo, 'id),
```

**Comment by martijndeh** [comment]
I did some initial experiments with a different API but because it's referencing itself during initialisation (of the type) it's not possible to create a straightforward api to achieve this. If anyone has a good suggestion, feel free to let me know!

In the meantime I'm thinking of a different api but I prefer to stick as close to SQL as possible.

**Comment by martijndeh** [comment]
This is now supported. The syntax is as below:

```
fooId: uuid().referencesSelf('id'),
```

This is not ideal because it's deviating from Postgres syntax, so it will likely change in the future, but at least this fixes this issue for now.

The cli is also updated to support this new syntax.
