### ISSUE TITLE
Documentation recommendation

### ISSUE THREAD

**Issue by vriad** [Ff00ff/mammoth#22]
For starters: love what you've done here. Definitely fills a need, so I want this lib to be successful. 

But I think the README is structured poorly, to the point of being alienating to a potential new user. 

This is the first bit of code in the readme:

```ts
const rows = await select(list.id, list.createdAt)
  .from(list)
  .where(list.createdAt.gt(now().minus(`2 days`)).or(list.value.eq(0)))
  .limit(10);
```

What's "list" and where does it come from? It just appears in your sample code. How do you import the module? 

After reading the full readme the picture becomes clear(ish) but you should start the Readme with the "Schema" section so its clear how to define a Mammoth class (and how you provide static type information to Typescript) before talking about operations you can make using that class. 

This lib deserves more attention than it's getting currently! Keep up the good work! I ended up here after you got a shoutout here: https://news.ycombinator.com/item?id=22739121 so I expect many people are discovering this at the moment.

PS Shouldn't "list" be capitalized in most of the sample code?

**Comment by martijndeh** [comment]
Thank you! I appreciate the advice and I agree it causes confusion. I have spent too little effort on getting the docs and any other getting started content in shape which makes it really hard to start using this library. I'll clear this up in the coming days!

I think this library is nearing feature parity with e.g. knexjs (but postgres only). I'm working on subqueries right now and CTEs are next. But everything is type-safe which is awesome of course! ;-)

**Comment by IgorSzymanski** [comment]
I also really enjoy this library.

I think I could help during the upcoming weekend with the docs as I've spent a few past days studying the library, as I was looking for a type-safe solution that would help me ditch ORMs once and for all (I hate ORMs).

It would also be nice to open issues regarding some design decisions that you question in `TODO` comments, if you're open to suggestions.

```
// TODO: You cannot drop a value. You must drop the type and re-create the type without the value. Is this something we want to do automatically?
```

**Comment by martijndeh** [comment]
Great to hear.

Yes of course, go ahead.

I'm also in https://gitter.im/ff00ff if you want to have a chat.

**Comment by martijndeh** [comment]
I just pushed some changes I've been working on the last few months. These are available on npm at `@ff00ff/mammoth@1.0.0-beta.9` now.

I update the README to clarify as suggested, so I'll close this issue. Improving the documentation is an ongoing effort so I'm not considering this resolved. If you have any other specific feedback please let me know.

Regarding the changes:

- There are some initial type check tests which should increase the stability and maintainability of the library. They are automatically checking some things which was previously easy to break.
- I'm introducing a new syntax to define tables which avoids using classes. I prefer this syntax because it feels more typescript idiomatic to me.
- Several type issues have been fixed which helps you catch bugs early. :)

**Comment by vriad** [comment]
Wow man this is excellent - great job. The CLI is super impressive too.

A few observations/questions/issues.

1. You have an unfinished sentence under Raw Queries: "Because type information is lost when using raw queries, you can..."

2. Still nothing about how to import the module. On a related note: for some reason a bunch of functions (uuid, createTable) aren't being exported in the module. I looked at your code and couldn't figure out why this was happening...it's pretty odd.
![Screen Shot 2020-04-03 at 4 25 05 PM](https://user-images.githubusercontent.com/3084745/78412306-b131e400-75c7-11ea-82e6-15b67c8f7dc4.png)

3. I suggest establishing a convention of importing all methods as a variable. That is: `import m from "@ff00ff/mammoth"; const list = m.defineTable( // ... )`. Makes it easy to see at a glance what code is mammoth-related, and you don't have to worry about cluttering up the local namespace with functions like "uuid" that are likely to have conflicts.

4. I also feel like it's more conventional to use capital letters when dealing with schema models, even in the TS/JS community. Objection, TypeORM, Sequelize, etc all use capitals by convention. That's your call though. 

5. I'd appreciate seeing a section about type inference for relations. You're definitely limited by typescript here, so it makes sense to be upfront about those limitations. It'll probably spare you from dealing with a bunch of issues in the future complaining about incorrect inferred types too :) I believe its possible to infer types on one-to-one and many-to-one relations; that is, you can infer the relation type for the model that holds the foreign key. Is there any way to fetch, say, a List and all its ListItems and still get static typing?

6. JOINS: Seem's odd they're not mentioned at all (even if it's on a todo list 😁)

7. You may want to consider generating the `db` object with code generation, it would let you do things like inferred relation types (including recursive relations) and a better `.select` API like the one used in [mst-gql](https://github.com/mobxjs/mst-gql#customizing-the-query-result) where you just "dot together" all the fields you want. Can't be done with just type inference sadly since it requires a custom getter defined for each property.

Just wanted to put all this out there in one go, but I'm happy to create separate issues if you think that's useful. Just let me know which numbers (if any) you'd like an issue for.

**Comment by vriad** [comment]
Realized you might not get a notification now that the issue is closed: @martijndeh

**Comment by martijndeh** [comment]
> Still nothing about how to import the module. On a related note: for some reason a bunch of functions (uuid, createTable) aren't being exported in the module. I looked at your code and couldn't figure out why this was happening...it's pretty odd.

I clarified the install procedure. The changes are available under a beta tag in npm. So to install you have to run `npm i @ff00ff/mammoth@1.0.0-beta.9`. Does this fix the issue for you?

> You may want to consider generating the db object with code generation, it would let you do things like inferred relation types (including recursive relations) and a better .select API like the one used in mst-gql where you just "dot together" all the fields you want. Can't be done with just type inference sadly since it requires a custom getter defined for each property.

The thing I wanted to avoid with mammoth is having to need a build step or watch running. If we ever add a build step, considering one of the other goals is trying to stick to SQL as close as possible (because that's what we all know, and that knowledge is reusable across projects), it probably makes most sense to generate types for raw queries and define your schema using, again, raw SQL (in for example migrations). So I don't think this project will ever get a build step.

> You should write up a blog post complaining about the dangers of non-type safe database access without static type guarantees, yadda yadda, then tell people about this lib.
Yea this is coming. :)

> Is the CLI implemented? Documentation? If you're still working on it you may want to look at the code for Prisma's CLI, which supports Postgres introspection. You may be able to use some of their code to convert a SQL schema to a structured representation in Javascript-land.
The CLI needs some love. There is an initial version but I'm rewriting the automatic migration generator. It used to have a custom query parser, but now I'm switching to the actual postgres query parser. I'll have a look at Prisma! I did check TypeORM, but I noticed they're actually using the local typeorm models and the schema of the database to diff changes. I think it makes more sense to diff the migrations and the local table files.

---

Thanks for the feedback. Feel free to improve the readme by creating a pull request. ;) I'm also going to set up a documentation site to include some of the use cases you're mentioning.
