### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by RXminuS** [Ff00ff/mammoth#76]
I don't really want to use Mammoth because it relies on migrations or manually maintained schemas. Rather I'd use something like Prisma 2 where I just setup my Postgres database and run some introspection query to generate the correct schema file.

However, I don't want to use Prisma 2 because they're adding too much abstraction/magic on top of SQL. I'd much rather use mammoth that's just a thin veneer of Typescript on top of SQL query builder.

So here is a proposal to pick&mix the best of both worlds...adding a "introspect" command to the cli. It would parse the specified Postgres schemas and generate as close a matching mammoth schema.

It's going to be quite an undertaking so just wanted to see if you're interested in actually seeing a PR for this or if we should rather just fork this project since it seems to go directly against one of your "core features".

Sadly there isn't a lot of code we can borrow from Prisma 2 (since core logic is in Rust) but it can definitely drive a lot of the design to get us started and if we'd make an on-par MVP we'd be able to use:

- domains, enums, types etc,
- core column types
- views
- foreign keys
- checks
- defaults
- ...

Thoughts?

**Comment by dmfay** [comment]
If you want something to crib from there's [MassiveJS](https://gitlab.com/dmfay/massive-js): also Postgres-only, loads enums, foreign tables, views, schemas, functions, and sql scripts, _but_ no types or TypeScript so you're on your own there.

**Comment by RXminuS** [comment]
Interesting, but what I think I like about mammoth is specifically that it doesn't add any "smart function" wrappers around SQL. For instance rather than having a function `findOne` like in Massive-sj there's just an entry point to a query...and if you want one item, SQL already has the `limit` operator.

Nothing bad about massive-js, but I see an opportunity for Mammoth to just be a super thin layer around SQL that makes it type safe w.r.t. a specific database...something that I haven't really seen before.

Also...this is just my opinion; this is not my project so take everything I say with a massive container of salt ;-)

**Comment by dmfay** [comment]
I'm not suggesting you use Massive instead (that would be terribly impolite here of all places) -- I'm saying that you and/or mammoth could lift the introspection code it already has! Massive does different things with the schema information but the process of _getting_ it will be pretty similar. There's no need to start from scratch.

**Comment by RXminuS** [comment]
Ah! So sorry, my bad...completely misunderstood. Thank you!

**Comment by martijndeh** [comment]
So just to give my overdue reply hehe: I reduced the scope of this library a bit so some of these ideas can be iterated on separate from this library (or me) and don't require a fork anymore.

Personally, I rather want to stick to SQL instead of adding another abstraction like Prisma (or whatnot). In my ideal world I have an SQL schema I manage through Mammoth (which indeed is TypeScript-as-close-to-SQL-as-possible as you know it). And with a `mammoth-cli create-migration` it creates a `001.sql`, `002.sql`, etc because on the SQL schema and all the migrations. Some take a slightly different approach by reading the current state from a remote database schema but I don't find that practical: means you need to migrate every time you switch branches etc.

Anyway, I want to start focusing on the query building aspect for now and some more marketing before increasing the scope again. So I won't be working on this any time soon. There is some code in this repo which did take steps in that direction though (sql-simulator and sql-creator specifically).
